// Regenerates src/styles/palette.css:  node scripts/genpalette.mjs > src/styles/palette.css
// iOS-system-colour ramps, expressed with color-mix so everything stays in CSS.
const base = {
  blue:"#0a84ff", sky:"#64b5ff", cyan:"#32ade6", teal:"#2ab8c4", emerald:"#30c25a", green:"#30c25a", lime:"#8fd13f",
  yellow:"#ffd60a", amber:"#ffb21a", orange:"#ff9f0a", red:"#ff453a", rose:"#ff4d6d", pink:"#ff4f8b",
  fuchsia:"#d65bdc", purple:"#b45cf0", indigo:"#5e5ce6",
};
const stops = {50:[8,"white"],100:[16,"white"],200:[30,"white"],300:[52,"white"],400:[76,"white"],500:[100],600:[84,"black"],700:[66,"black"],800:[50,"black"],900:[36,"black"],950:[24,"black"]};
let out = "/* GENERATED by genpalette.mjs - iOS system colour ramps. Do not hand-edit. */\n@theme {\n";
for (const [name,hex] of Object.entries(base)) for (const [s,[p,mix]] of Object.entries(stops)) {
  out += `  --color-${name}-${s}: ${mix? `color-mix(in oklab, ${hex} ${p}%, ${mix})` : hex};\n`;
}
// brand "violet" follows the role accent
for (const [s,[p,mix]] of Object.entries(stops)) {
  out += `  --color-violet-${s}: ${mix? `color-mix(in oklab, var(--accent) ${p}%, ${mix})` : "var(--accent)"};\n`;
}
out += "}\n";
// Dark mode: pale tints become translucent glows, deep text shades become light,
// so class lists written for a light page stay legible on dark glass.
const dark = {50:[9,"transparent"],100:[15,"transparent"],200:[24,"transparent"],300:[40,"transparent"],400:[100,"white",14],500:[100],600:[88,"white"],700:[62,"white"],800:[46,"white"],900:[30,"white"],950:[18,"white"]};
out += "\n@layer base {\n  .dark {\n";
const all = {...base, violet:"var(--accent)"};
for (const [name,hex] of Object.entries(all)) for (const [sh,[p,mix,extra]] of Object.entries(dark)) {
  let v;
  if (mix==="transparent") v = `color-mix(in oklab, ${hex} ${p}%, transparent)`;
  else if (sh==="400") v = `color-mix(in oklab, ${hex} 86%, white)`;
  else if (!mix) v = hex;
  else v = `color-mix(in oklab, ${hex} ${p}%, ${mix})`;
  out += `    --color-${name}-${sh}: ${v};\n`;
}
out += "  }\n}\n";
console.log(out);
